testthat::test_that("Consumer Shopping Trends Beta está integrado ao padrão do repositório", {
  testthat::expect_true(file.exists(file.path("scripts", "consumer_shopping_trends_beta", "consumer_shopping_trends_beta_rstan.R")))
  testthat::expect_true(file.exists(file.path("scripts", "consumer_shopping_trends_beta", "README.md")))
  testthat::expect_true(file.exists(file.path("data", "raw", "consumer_shopping_trends", ".gitkeep")))
  testthat::expect_true(file.exists(file.path("data", "raw", "consumer_shopping_trends", "README.md")))
  testthat::expect_true(file.exists(file.path("outputs", "figures", "consumer_shopping_trends_beta", ".gitkeep")))
  testthat::expect_true(file.exists(file.path("outputs", "tables", "consumer_shopping_trends_beta", ".gitkeep")))
  testthat::expect_true(file.exists(file.path("outputs", "models", "consumer_shopping_trends_beta", ".gitkeep")))

  readme_root <- readLines("README.md", warn = FALSE, encoding = "UTF-8")
  readme_scripts <- readLines(file.path("scripts", "README.md"), warn = FALSE, encoding = "UTF-8")
  readme_data <- readLines(file.path("data", "raw", "README.md"), warn = FALSE, encoding = "UTF-8")
  gitignore <- readLines(".gitignore", warn = FALSE, encoding = "UTF-8")
  script_lines <- readLines(file.path("scripts", "consumer_shopping_trends_beta", "consumer_shopping_trends_beta_rstan.R"), warn = FALSE, encoding = "UTF-8")

  testthat::expect_true(any(grepl("Consumer Shopping Trends", readme_root, fixed = TRUE)))
  testthat::expect_true(any(grepl("consumer_shopping_trends_beta_rstan.R", readme_scripts, fixed = TRUE)))
  testthat::expect_true(any(grepl("data/raw/consumer_shopping_trends/", readme_data, fixed = TRUE)))
  testthat::expect_true(any(grepl("data/raw/consumer_shopping_trends/\\*\\*", gitignore)))
  testthat::expect_true(any(grepl("avg_online_spend", script_lines, fixed = TRUE)))
  testthat::expect_true(any(grepl("avg_store_spend", script_lines, fixed = TRUE)))
  testthat::expect_true(any(grepl("rstan_options(auto_write = FALSE)", script_lines, fixed = TRUE)))
})
